# Generated by Django 4.2.7 on 2023-11-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foodDay", models.CharField(max_length=200)),
                ("foodChoice", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="MealEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("snacks", "Snacks"),
                        ],
                        max_length=20,
                    ),
                ),
                ("food_item", models.CharField(max_length=100)),
                ("calories_consumed", models.PositiveIntegerField()),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
