# Generated by Django 4.2.6 on 2023-10-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foodDay", models.CharField(max_length=200)),
                ("foodChoice", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="WorkOutVideos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workOutDay", models.CharField(max_length=200)),
                ("workOutVideoLink", models.CharField(max_length=200)),
            ],
        ),
    ]
