# Generated by Django 4.2.6 on 2023-10-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mmc", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workout",
            name="date",
        ),
        migrations.AlterField(
            model_name="workout",
            name="workout_type",
            field=models.CharField(
                choices=[
                    ("Cardio", "Cardio"),
                    ("Strength Training", "Strength Training"),
                    ("Yoga", "Yoga"),
                ],
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="Chart",
        ),
    ]
