# Generated by Django 4.2.6 on 2023-10-29 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmc', '0002_alter_userprofile_type_of_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='custom_user',
        ),
    ]
