# Generated by Django 4.2.6 on 2023-11-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_userprofile_gender_alter_userprofile_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type_of_account',
            field=models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid'), ('Trainer', 'Trainer')], default='Free', max_length=10),
        ),
    ]
