# Generated by Django 4.2.6 on 2023-11-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0005_alter_userprofile_type_of_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="type_of_account",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_free_account",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_paid_account",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_trainer_account",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                choices=[(1, "Female"), (2, "Male"), (3, "Other")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="height",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(
                blank=True, default="1-123-456-7890", max_length=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
