# Generated by Django 4.2.6 on 2023-11-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0006_remove_userprofile_type_of_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.IntegerField(
                choices=[(1, "Female"), (2, "Male"), (3, "Other")]
            ),
        ),
    ]
