# Generated by Django 4.2.6 on 2023-11-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0008_alter_userprofile_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.IntegerField(choices=[]),
        ),
    ]
