# Generated by Django 4.2.6 on 2023-11-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0010_alter_userprofile_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.IntegerField(
                choices=[(1, "Female"), (2, "Male"), (3, "Other")], default=2
            ),
        ),
    ]
